require('express')()
.set('view engine', 'jsx')
.set('views', __dirname + '/pages')
.engine('jsx', require('express-react-views').createEngine())
.get('/', (req, { render }) => render('index'))
.get('/script', (req, { sendFile }) => sendFile(__dirname + '/pages/script.js')) 
.listen(8000)